"""Add Phase 2 employee and explanation fields

Revision ID: 69bc67fd2582
Revises: fdcff17e92d0
Create Date: 2026-06-02 13:31:04.455120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bc67fd2582'
down_revision: Union[str, Sequence[str], None] = 'fdcff17e92d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_transactions', sa.Column('employee_id', sa.String(length=64), nullable=True))
    op.add_column('receipt_transactions', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('receipt_transactions', sa.Column('explanation_submit_dt', sa.DateTime(), nullable=True))
    op.add_column('receipt_transactions', sa.Column('explanation_content', sa.String(length=4000), nullable=True))
    op.add_column('receipt_transactions', sa.Column('is_escalated', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    op.create_index(op.f('ix_receipt_transactions_employee_id'), 'receipt_transactions', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_transactions_employee_id'), table_name='receipt_transactions')
    op.drop_column('receipt_transactions', 'is_escalated')
    op.drop_column('receipt_transactions', 'explanation_content')
    op.drop_column('receipt_transactions', 'explanation_submit_dt')
    op.drop_column('receipt_transactions', 'due_date')
    op.drop_column('receipt_transactions', 'employee_id')
    # ### end Alembic commands ###
