"""Add compliance audit fields

Revision ID: 7d2164854de5
Revises: d4c6feae73d5
Create Date: 2026-06-01 18:16:16.282792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2164854de5'
down_revision: Union[str, Sequence[str], None] = 'd4c6feae73d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: SQLite/PostgreSQL 호환을 위해 text('true') 사용 (text('1')은 PG boolean에서 거부됨)
    op.add_column('receipt_transactions', sa.Column('is_compliant', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('receipt_transactions', sa.Column('violation_reason', sa.String(length=1024), nullable=True))
    op.add_column('receipt_transactions', sa.Column('explanation_status', sa.String(length=16), nullable=True))
    op.add_column('receipt_transactions', sa.Column('explanation_request_dt', sa.DateTime(), nullable=True))
    op.add_column('receipt_transactions', sa.Column('explanation_requester', sa.String(length=64), nullable=True))
    op.add_column('receipt_transactions', sa.Column('explanation_process_dt', sa.DateTime(), nullable=True))
    op.add_column('receipt_transactions', sa.Column('explanation_processor', sa.String(length=64), nullable=True))
    op.add_column('receipt_transactions', sa.Column('explanation_request_msg', sa.String(length=2048), nullable=True))
    op.add_column('receipt_transactions', sa.Column('explanation_process_comment', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_transactions', 'explanation_process_comment')
    op.drop_column('receipt_transactions', 'explanation_request_msg')
    op.drop_column('receipt_transactions', 'explanation_processor')
    op.drop_column('receipt_transactions', 'explanation_process_dt')
    op.drop_column('receipt_transactions', 'explanation_requester')
    op.drop_column('receipt_transactions', 'explanation_request_dt')
    op.drop_column('receipt_transactions', 'explanation_status')
    op.drop_column('receipt_transactions', 'violation_reason')
    op.drop_column('receipt_transactions', 'is_compliant')
    # ### end Alembic commands ###
