"""Add transaction models

Revision ID: d4c6feae73d5
Revises: d4e323196d2b
Create Date: 2026-05-28 18:36:59.667613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c6feae73d5'
down_revision: Union[str, Sequence[str], None] = 'd4e323196d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('workplace_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_files_company_id'), 'receipt_files', ['company_id'], unique=False)
    op.create_index(op.f('ix_receipt_files_workplace_id'), 'receipt_files', ['workplace_id'], unique=False)
    op.create_table('receipt_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('workplace_id', sa.String(length=64), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('receipt_time', sa.String(length=8), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=False),
    sa.Column('merchant_sector_code', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('recommended_category_code', sa.String(length=64), nullable=False),
    sa.Column('recommended_result_category', sa.String(length=255), nullable=False),
    sa.Column('applied_rule_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('is_manually_modified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['receipt_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_transactions_company_id'), 'receipt_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_receipt_transactions_file_id'), 'receipt_transactions', ['file_id'], unique=False)
    op.create_index(op.f('ix_receipt_transactions_workplace_id'), 'receipt_transactions', ['workplace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_transactions_workplace_id'), table_name='receipt_transactions')
    op.drop_index(op.f('ix_receipt_transactions_file_id'), table_name='receipt_transactions')
    op.drop_index(op.f('ix_receipt_transactions_company_id'), table_name='receipt_transactions')
    op.drop_table('receipt_transactions')
    op.drop_index(op.f('ix_receipt_files_workplace_id'), table_name='receipt_files')
    op.drop_index(op.f('ix_receipt_files_company_id'), table_name='receipt_files')
    op.drop_table('receipt_files')
    # ### end Alembic commands ###
