"""Initial tables

Revision ID: d4e323196d2b
Revises: 
Create Date: 2026-05-28 14:18:19.088537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e323196d2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('workplace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('receipt_amount', sa.Integer(), nullable=False),
    sa.Column('receipt_merchant', sa.String(length=255), nullable=False),
    sa.Column('receipt_date', sa.DateTime(), nullable=False),
    sa.Column('approved_category', sa.String(length=255), nullable=False),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_history_company_id'), 'approval_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_approval_history_workplace_id'), 'approval_history', ['workplace_id'], unique=False)
    op.create_table('company_receipt_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('workplace_id', sa.String(length=64), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('condition_keyword', sa.String(length=255), nullable=True),
    sa.Column('condition_min_amount', sa.Integer(), nullable=True),
    sa.Column('condition_max_amount', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('usage_time_band', sa.String(length=32), nullable=True),
    sa.Column('card_company_code', sa.String(length=32), nullable=True),
    sa.Column('merchant_sector_code', sa.String(length=32), nullable=True),
    sa.Column('merchant_sector_name', sa.String(length=255), nullable=True),
    sa.Column('category_code', sa.String(length=32), nullable=False),
    sa.Column('result_category', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_receipt_rules_company_id'), 'company_receipt_rules', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_receipt_rules_workplace_id'), 'company_receipt_rules', ['workplace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_receipt_rules_workplace_id'), table_name='company_receipt_rules')
    op.drop_index(op.f('ix_company_receipt_rules_company_id'), table_name='company_receipt_rules')
    op.drop_table('company_receipt_rules')
    op.drop_index(op.f('ix_approval_history_workplace_id'), table_name='approval_history')
    op.drop_index(op.f('ix_approval_history_company_id'), table_name='approval_history')
    op.drop_table('approval_history')
    # ### end Alembic commands ###
