"""add rag chatbot tables (bots, documents, chat_sessions, chat_messages, recommended_questions)

Revision ID: d5617aa3741a
Revises: c154a0912972
Create Date: 2026-06-05 14:11:53.280839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5617aa3741a'
down_revision: Union[str, Sequence[str], None] = 'c154a0912972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('workplace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('llm_temperature', sa.Float(), nullable=False),
    sa.Column('max_answer_length', sa.Integer(), nullable=False),
    sa.Column('history_turns', sa.Integer(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('source_expose', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'workplace_id', 'name', name='uq_bot_tenant_name')
    )
    op.create_index(op.f('ix_bots_company_id'), 'bots', ['company_id'], unique=False)
    op.create_index(op.f('ix_bots_workplace_id'), 'bots', ['workplace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('workplace_id', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=32), server_default=sa.text("'policy'"), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('is_compliance_source', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('embedding_status', sa.String(length=16), server_default=sa.text("'PROCESSING'"), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_domain'), 'documents', ['domain'], unique=False)
    op.create_index(op.f('ix_documents_is_compliance_source'), 'documents', ['is_compliance_source'], unique=False)
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documents_workplace_id'), 'documents', ['workplace_id'], unique=False)
    op.create_table('bot_recommended_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_recommended_questions_bot_id'), 'bot_recommended_questions', ['bot_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=64), nullable=False),
    sa.Column('workplace_id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), server_default=sa.text("'web'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_bot_id'), 'chat_sessions', ['bot_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_company_id'), 'chat_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_workplace_id'), 'chat_sessions', ['workplace_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_seq'), 'chat_messages', ['seq'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_seq'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_workplace_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_company_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_bot_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_bot_recommended_questions_bot_id'), table_name='bot_recommended_questions')
    op.drop_table('bot_recommended_questions')
    op.drop_index(op.f('ix_documents_workplace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_compliance_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_domain'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_bots_workplace_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_company_id'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
