"""Add department column to transaction

Revision ID: fdcff17e92d0
Revises: 7d2164854de5
Create Date: 2026-06-02 09:30:09.314676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdcff17e92d0'
down_revision: Union[str, Sequence[str], None] = '7d2164854de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_transactions', sa.Column('department', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_receipt_transactions_department'), 'receipt_transactions', ['department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_transactions_department'), table_name='receipt_transactions')
    op.drop_column('receipt_transactions', 'department')
    # ### end Alembic commands ###
